= Flow Logix, Inc.
:jbake-type: page
:description: About the Company
:idprefix:
:linkattrs:
:jbake-status: published

== Flow Logix - an Information Technology Consulting Firm
At Flow Logix, we develop software-based solutions for fast-moving businesses.
Utilizing Jakarta EE technology, our process is quick and our solutions are built for
maintainability and performance, thus minimizing overall costs.
We excel at developing distributed, real-time highly scalable systems.

We specialize in IT consulting services for the following industries:

- Transportation / Logistics
- Financial Services
- Aviation

== Our Process
We start by analyzing each client’s challenges. We drill down to discover root problems,
and define the parameters of each in order to create an executable strategy.
Abstract problems can quickly be turned into an actionable to-do list.
We see all projects through from design, to execution, to maintenance. 

Additionally, Flow Logix is an industry innovator and is constantly developing new products and services.

== What makes us different
We have the experience to identify root causes of many issues.
Having seen many iterations of technologies and common problems, we are able to solve them efficiently.

Our expertise and tenacity gives us a unique ability to develop creative solutions, even for complex projects.

Flow Logix is an industry innovator and is constantly developing new products and services.

=== Flow Logix is contributing to many Open Source projects
++++
<iframe src="https://github.com/sponsors/flowlogix/button" title="Sponsor FlowLogix" height="35" width="116" style="border: 0;"></iframe>
++++
{zwsp} +

== Read our blog
https://sensibledev.tumblr.com[Sensible Development Blog^] +
https://medium.com/@lennyprimak[Medium Blog^]

The Company also functions as https://hope.nyc.ny.us[Lenny Primak's] corporate entity.
